/* The following code was generated by JFlex 1.7.0 */

package smpl.syntax.lexer;

/* Specification for SMPL tokens */

// user customisations
import java_cup.runtime.*;

import smpl.exceptions.TokenException;

import smpl.syntax.parser.sym;

// Jlex directives
    

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/smpl/syntax/lexer/SMPLLexer</tt>
 */
public class SMPLLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\3\1\1\1\60\1\3\1\1\22\0\1\3\1\25"+
    "\1\57\1\7\1\0\1\15\1\17\1\63\1\36\1\37\1\12\1\13"+
    "\1\43\1\14\1\56\1\11\2\5\10\4\1\35\1\42\1\24\1\22"+
    "\1\23\1\0\1\34\32\6\1\10\1\61\1\10\1\16\1\0\1\0"+
    "\1\26\1\54\1\50\1\30\1\44\1\45\1\6\1\52\1\51\2\6"+
    "\1\46\1\6\1\27\1\31\1\47\1\6\1\32\1\53\1\33\1\62"+
    "\2\6\1\55\2\6\1\40\1\20\1\41\1\21\6\0\1\60\32\0"+
    "\1\60\u15df\0\1\60\u097f\0\13\60\35\0\2\60\5\0\1\60\57\0"+
    "\1\60\u0fa0\0\1\60\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\7\1\1\21\1\1\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\6\1\1\30\1\31\1\32\1\33"+
    "\2\34\1\35\1\36\4\1\1\34\1\37\1\40\1\41"+
    "\3\34\1\42\2\34\1\43\4\34\1\44\1\45\1\46"+
    "\1\47\1\50\3\51\1\52\1\53\1\1\2\54\1\55"+
    "\1\56\1\57\3\34\1\60\4\34\1\61\1\62\1\63"+
    "\1\1\1\64\1\65\1\66\1\67\1\34\1\70\1\71"+
    "\1\1\1\34\1\72\1\73\2\34\1\74\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\150\0\234\0\320\0\u0104"+
    "\0\u0138\0\u016c\0\150\0\150\0\150\0\150\0\150\0\150"+
    "\0\150\0\150\0\150\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\u0340\0\150\0\u0374\0\u0138\0\u0138"+
    "\0\u0138\0\u0138\0\150\0\u0138\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\234\0\234\0\234\0\u04e0\0\150\0\u04ac"+
    "\0\u0138\0\u0138\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4\0\150"+
    "\0\150\0\150\0\u0618\0\u064c\0\u0680\0\150\0\u06b4\0\u06e8"+
    "\0\u0138\0\u071c\0\u0750\0\u0784\0\u07b8\0\150\0\u04ac\0\234"+
    "\0\234\0\234\0\u0138\0\234\0\u07ec\0\u0548\0\u057c\0\u0820"+
    "\0\234\0\u0854\0\150\0\150\0\150\0\u0888\0\u08bc\0\u08f0"+
    "\0\150\0\u0924\0\u0958\0\u098c\0\u09c0\0\u0138\0\u0138\0\u0138"+
    "\0\u09f4\0\u0a28\0\150\0\150\0\150\0\u0a5c\0\150\0\150"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\u0138\0\u0b2c\0\u0b60\0\150\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\7\1\3\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\3\1\46\1\47\1\50"+
    "\1\51\4\3\1\52\1\53\1\0\2\3\1\0\1\54"+
    "\1\0\55\54\1\55\1\54\1\56\2\54\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\24\57\5\11\1\57\1\11"+
    "\13\57\2\0\2\57\65\0\1\57\1\0\1\57\1\0"+
    "\2\7\2\57\1\11\24\57\5\11\1\57\1\11\12\57"+
    "\1\60\2\0\2\57\1\0\1\11\1\0\1\11\1\0"+
    "\27\11\1\61\10\11\1\62\1\61\2\11\1\63\3\11"+
    "\1\64\1\65\1\11\2\0\1\11\1\66\1\0\1\11"+
    "\1\0\1\11\1\0\53\11\2\0\2\11\1\0\1\57"+
    "\1\0\1\57\1\0\4\57\1\11\1\67\23\57\5\11"+
    "\1\57\1\11\13\57\2\0\2\57\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\11\57\1\70\12\57\5\11"+
    "\1\57\1\11\13\57\2\0\2\57\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\11\57\1\71\12\57\5\11"+
    "\1\57\1\11\13\57\2\0\2\57\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\11\57\1\72\12\57\5\11"+
    "\1\57\1\11\13\57\2\0\2\57\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\16\57\1\73\5\57\5\11"+
    "\1\57\1\11\13\57\2\0\2\57\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\20\57\1\74\3\57\5\11"+
    "\1\57\1\11\13\57\2\0\2\57\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\24\57\5\11\1\57\1\11"+
    "\1\75\12\57\2\0\2\57\1\0\1\57\1\0\1\57"+
    "\1\0\4\57\1\11\21\57\1\76\2\57\5\11\1\57"+
    "\1\11\13\57\2\0\2\57\1\0\1\57\1\0\1\57"+
    "\1\0\4\57\1\11\24\57\5\11\1\57\1\11\1\77"+
    "\12\57\2\0\2\57\1\0\1\57\1\0\1\57\1\0"+
    "\4\57\1\11\24\57\5\11\1\57\1\11\6\57\1\100"+
    "\4\57\2\0\2\57\1\0\1\11\1\0\1\11\1\0"+
    "\16\11\1\101\34\11\2\0\2\11\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\24\57\5\11\1\57\1\11"+
    "\2\57\1\102\10\57\2\0\2\57\1\0\1\57\1\0"+
    "\1\57\1\0\4\57\1\11\24\57\5\11\1\57\1\11"+
    "\1\103\12\57\2\0\2\57\1\0\1\57\1\0\1\57"+
    "\1\0\4\57\1\11\21\57\1\104\2\57\5\11\1\57"+
    "\1\11\13\57\2\0\2\57\1\0\1\57\1\0\1\57"+
    "\1\0\4\57\1\11\15\57\1\105\6\57\5\11\1\57"+
    "\1\11\13\57\2\0\2\57\1\0\1\57\1\0\1\57"+
    "\1\0\4\57\1\11\24\57\5\11\1\57\1\11\1\57"+
    "\1\106\11\57\2\0\2\57\1\0\1\57\1\0\1\57"+
    "\1\0\2\107\2\57\1\11\24\57\5\11\1\57\1\11"+
    "\13\57\2\0\2\57\30\0\1\110\3\0\1\111\23\0"+
    "\1\112\4\0\1\113\1\0\1\113\1\0\53\113\1\114"+
    "\1\0\1\115\1\113\1\114\1\11\1\0\1\11\1\0"+
    "\1\11\1\116\51\11\2\0\2\11\1\0\1\11\1\0"+
    "\1\11\1\0\3\117\17\11\6\117\10\11\12\117\1\11"+
    "\2\0\1\11\1\117\1\0\1\11\1\0\1\11\1\0"+
    "\3\120\17\11\6\120\10\11\12\120\1\11\2\0\1\11"+
    "\1\120\1\0\1\67\1\121\1\67\1\122\4\67\1\122"+
    "\24\67\5\122\1\67\1\122\13\67\2\122\2\67\1\122"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\17\57\1\123"+
    "\4\57\5\11\1\57\1\11\13\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\22\57\1\124"+
    "\1\57\5\11\1\57\1\11\13\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\24\57\5\11"+
    "\1\57\1\11\1\57\1\125\11\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\15\57\1\126"+
    "\6\57\5\11\1\57\1\11\13\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\24\57\5\11"+
    "\1\57\1\11\1\127\12\57\2\0\2\57\1\0\1\57"+
    "\1\0\1\57\1\0\4\57\1\11\24\57\5\11\1\57"+
    "\1\11\7\57\1\130\3\57\2\0\2\57\1\0\1\57"+
    "\1\0\1\57\1\0\4\57\1\11\22\57\1\131\1\57"+
    "\5\11\1\57\1\11\13\57\2\0\2\57\1\0\1\57"+
    "\1\0\1\57\1\0\4\57\1\11\20\57\1\132\3\57"+
    "\5\11\1\57\1\11\5\57\1\133\5\57\2\0\2\57"+
    "\1\0\1\57\1\0\1\57\1\0\4\57\1\11\24\57"+
    "\5\11\1\57\1\11\2\57\1\134\4\57\1\135\3\57"+
    "\2\0\2\57\1\0\1\11\1\0\1\11\1\0\23\11"+
    "\1\136\3\11\1\137\23\11\2\0\1\140\1\11\1\0"+
    "\1\11\1\0\1\11\1\0\3\141\17\11\6\141\10\11"+
    "\12\141\1\11\2\0\1\11\1\141\1\0\1\122\1\121"+
    "\62\122\1\57\1\0\1\57\1\0\4\57\1\11\17\57"+
    "\1\142\4\57\5\11\1\57\1\11\13\57\2\0\2\57"+
    "\1\0\1\57\1\0\1\57\1\0\4\57\1\11\16\57"+
    "\1\143\5\57\5\11\1\57\1\11\13\57\2\0\2\57"+
    "\1\0\1\57\1\0\1\57\1\0\4\57\1\11\24\57"+
    "\5\11\1\57\1\11\1\144\12\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\24\57\5\11"+
    "\1\57\1\11\4\57\1\145\6\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\16\57\1\146"+
    "\5\57\5\11\1\57\1\11\13\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\24\57\5\11"+
    "\1\57\1\11\2\57\1\147\10\57\2\0\2\57\1\0"+
    "\1\57\1\0\1\57\1\0\4\57\1\11\24\57\5\11"+
    "\1\57\1\11\1\150\12\57\2\0\2\57\1\0\1\11"+
    "\1\0\1\11\1\0\3\151\17\11\6\151\10\11\12\151"+
    "\1\11\2\0\1\11\1\151\1\0\1\57\1\0\1\57"+
    "\1\0\4\57\1\11\24\57\5\11\1\57\1\11\5\57"+
    "\1\152\5\57\2\0\2\57\1\0\1\57\1\0\1\57"+
    "\1\0\4\57\1\11\22\57\1\153\1\57\5\11\1\57"+
    "\1\11\13\57\2\0\2\57\1\0\1\11\1\0\1\11"+
    "\1\0\3\154\17\11\6\154\10\11\12\154\1\11\2\0"+
    "\1\11\1\154\1\0\1\57\1\0\1\57\1\0\4\57"+
    "\1\11\16\57\1\155\5\57\5\11\1\57\1\11\13\57"+
    "\2\0\2\57\1\0\1\57\1\0\1\57\1\0\4\57"+
    "\1\11\24\57\5\11\1\57\1\11\2\57\1\156\10\57"+
    "\2\0\2\57\1\0\1\57\1\0\1\57\1\0\4\57"+
    "\1\11\22\57\1\157\1\57\5\11\1\57\1\11\13\57"+
    "\2\0\2\57\1\0\1\57\1\0\1\57\1\0\4\57"+
    "\1\11\16\57\1\160\5\57\5\11\1\57\1\11\13\57"+
    "\2\0\2\57\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2964];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\1\1\1\11\44\1\3\11\32\1"+
    "\3\11\1\1\1\11\4\1\1\11\37\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer string = new StringBuffer();

    public int getChar() {
	    return yychar + 1;
    }

    public int getColumn() {
    	return yycolumn + 1;
    }

    public int getLine() {
	    return yyline + 1;
    }

    public String getText() {
	    return yytext();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public SMPLLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, TokenException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { // ensures all tokens without whitespace separating excluding
    // quotations, parentheses, brackets, braces, colons and commas are
    // caught and dealt with as an error if it doesn't match any of our 
    // language's rules.
    String msg = String.format("Unrecognised Token: %s", yytext());
    throw new TokenException(msg);
            } 
            // fall through
          case 62: break;
          case 2: 
            { //skip newline, but reset char counter
    yychar = 0;
            } 
            // fall through
          case 63: break;
          case 3: 
            { /* skip whitespace */
            } 
            // fall through
          case 64: break;
          case 4: 
            { // INTEGER
    return new Symbol(sym.INT, 
            new Integer(yytext()));
            } 
            // fall through
          case 65: break;
          case 5: 
            { return new Symbol(sym.DIV);
            } 
            // fall through
          case 66: break;
          case 6: 
            { return new Symbol(sym.MUL);
            } 
            // fall through
          case 67: break;
          case 7: 
            { return new Symbol(sym.PLUS);
            } 
            // fall through
          case 68: break;
          case 8: 
            { return new Symbol(sym.MINUS);
            } 
            // fall through
          case 69: break;
          case 9: 
            { return new Symbol(sym.MOD);
            } 
            // fall through
          case 70: break;
          case 10: 
            { return new Symbol(sym.POW);
            } 
            // fall through
          case 71: break;
          case 11: 
            { return new Symbol(sym.BAND);
            } 
            // fall through
          case 72: break;
          case 12: 
            { return new Symbol(sym.BOR);
            } 
            // fall through
          case 73: break;
          case 13: 
            { return new Symbol(sym.BNOT);
            } 
            // fall through
          case 74: break;
          case 14: 
            { return new Symbol(sym.EQ);
            } 
            // fall through
          case 75: break;
          case 15: 
            { return new Symbol(sym.GT);
            } 
            // fall through
          case 76: break;
          case 16: 
            { return new Symbol(sym.LT);
            } 
            // fall through
          case 77: break;
          case 17: 
            { return new Symbol(sym.CONCAT);
            } 
            // fall through
          case 78: break;
          case 18: 
            { return new Symbol(sym.LPAREN);
            } 
            // fall through
          case 79: break;
          case 19: 
            { return new Symbol(sym.RPAREN);
            } 
            // fall through
          case 80: break;
          case 20: 
            { return new Symbol(sym.LBRACE);
            } 
            // fall through
          case 81: break;
          case 21: 
            { return new Symbol(sym.RBRACE);
            } 
            // fall through
          case 82: break;
          case 22: 
            { return new Symbol(sym.SEMI);
            } 
            // fall through
          case 83: break;
          case 23: 
            { return new Symbol(sym.COMMA);
            } 
            // fall through
          case 84: break;
          case 24: 
            { // STRING
    string.setLength(0); yybegin(STRING);
            } 
            // fall through
          case 85: break;
          case 25: 
            { string.append(yytext());
            } 
            // fall through
          case 86: break;
          case 26: 
            { yybegin(YYINITIAL);
                        return new Symbol(sym.STRING,
                        string.toString());
            } 
            // fall through
          case 87: break;
          case 27: 
            { string.append('\\');
            } 
            // fall through
          case 88: break;
          case 28: 
            { // IDENTIFIER
    return new Symbol(sym.ID, yytext());
            } 
            // fall through
          case 89: break;
          case 29: 
            { // BOOLEAN
    // get the letter after the # sign
    char val = yycharat(1);
    if (val == 't') {
        return new Symbol(sym.BOOLEAN,
            new Boolean(true));
    }
    return new Symbol(sym.BOOLEAN,
        new Boolean(false));
            } 
            // fall through
          case 90: break;
          case 30: 
            { return new Symbol(sym.NIL);
            } 
            // fall through
          case 91: break;
          case 31: 
            { return new Symbol(sym.GTEQ);
            } 
            // fall through
          case 92: break;
          case 32: 
            { return new Symbol(sym.LTEQ);
            } 
            // fall through
          case 93: break;
          case 33: 
            { return new Symbol(sym.NEQ);
            } 
            // fall through
          case 94: break;
          case 34: 
            { return new Symbol(sym.OR);
            } 
            // fall through
          case 95: break;
          case 35: 
            { return new Symbol(sym.ASSIGN);
            } 
            // fall through
          case 96: break;
          case 36: 
            { return new Symbol(sym.IF);
            } 
            // fall through
          case 97: break;
          case 37: 
            { // DOUBLE
    return new Symbol(sym.DOUBLE,
            new Double(yytext()));
            } 
            // fall through
          case 98: break;
          case 38: 
            { string.append('\n');
            } 
            // fall through
          case 99: break;
          case 39: 
            { string.append('\t');
            } 
            // fall through
          case 100: break;
          case 40: 
            { string.append('\"');
            } 
            // fall through
          case 101: break;
          case 41: 
            { // CHARACTER
    char val = yycharat(2);
    return new Symbol(sym.CHARACTER, 
        new Character(val));
            } 
            // fall through
          case 102: break;
          case 42: 
            { // BINARY
    String val = yytext().substring(2);
    return new Symbol(sym.INT,
        Integer.parseInt(val, 2));
            } 
            // fall through
          case 103: break;
          case 43: 
            { // HEXADECIMAL
    String val = yytext().substring(2);
    return new Symbol(sym.INT,
        Integer.parseInt(val, 16));
            } 
            // fall through
          case 104: break;
          case 44: 
            { /* Ignore any comments */
            } 
            // fall through
          case 105: break;
          case 45: 
            { return new Symbol(sym.AND);
            } 
            // fall through
          case 106: break;
          case 46: 
            { return new Symbol(sym.NOT);
            } 
            // fall through
          case 107: break;
          case 47: 
            { return new Symbol(sym.DEF);
            } 
            // fall through
          case 108: break;
          case 48: 
            { return new Symbol(sym.LET);
            } 
            // fall through
          case 109: break;
          case 49: 
            { // ESCAPED CHARACTER \n
    return new Symbol(sym.CHARACTER, 
        new Character('\n'));
            } 
            // fall through
          case 110: break;
          case 50: 
            { // ESCAPED CHARACTER \t
    return new Symbol(sym.CHARACTER, 
        new Character('\t'));
            } 
            // fall through
          case 111: break;
          case 51: 
            { // ESCAPED CHARACTER \
    return new Symbol(sym.CHARACTER, 
        new Character('\\'));
            } 
            // fall through
          case 112: break;
          case 52: 
            { return new Symbol(sym.READ);
            } 
            // fall through
          case 113: break;
          case 53: 
            { return new Symbol(sym.THEN);
            } 
            // fall through
          case 114: break;
          case 54: 
            { return new Symbol(sym.ELSE);
            } 
            // fall through
          case 115: break;
          case 55: 
            { return new Symbol(sym.PROC);
            } 
            // fall through
          case 116: break;
          case 56: 
            { return new Symbol(sym.CALL);
            } 
            // fall through
          case 117: break;
          case 57: 
            { return new Symbol(sym.CASE);
            } 
            // fall through
          case 118: break;
          case 58: 
            { return new Symbol(sym.PRINT);
            } 
            // fall through
          case 119: break;
          case 59: 
            { // UNICODE CHARACTER
    String val = yytext().substring(2);
    int ch = Integer.parseInt(val, 16);
    return new Symbol(sym.CHARACTER,
        new Character((char) ch));
            } 
            // fall through
          case 120: break;
          case 60: 
            { return new Symbol(sym.READINT);
            } 
            // fall through
          case 121: break;
          case 61: 
            { return new Symbol(sym.PRINTLN);
            } 
            // fall through
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
