
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package smpl.syntax.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 14;
  public static final int GTEQ = 22;
  public static final int LTEQ = 21;
  public static final int CONCAT = 27;
  public static final int READINT = 36;
  public static final int CASE = 40;
  public static final int DOUBLE = 43;
  public static final int LPAREN = 2;
  public static final int SEMI = 7;
  public static final int INT = 42;
  public static final int PRINTLN = 34;
  public static final int MINUS = 10;
  public static final int CHARACTER = 45;
  public static final int RPAREN = 3;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int LT = 20;
  public static final int NIL = 28;
  public static final int OR = 25;
  public static final int COMMA = 6;
  public static final int CALL = 32;
  public static final int BAND = 15;
  public static final int DIV = 12;
  public static final int BNOT = 17;
  public static final int PLUS = 9;
  public static final int IF = 37;
  public static final int ASSIGN = 8;
  public static final int ID = 41;
  public static final int BOOLEAN = 46;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MUL = 11;
  public static final int MOD = 13;
  public static final int NEQ = 23;
  public static final int EQ = 18;
  public static final int ELSE = 39;
  public static final int BOR = 16;
  public static final int LBRACE = 4;
  public static final int READ = 35;
  public static final int LET = 30;
  public static final int THEN = 38;
  public static final int RBRACE = 5;
  public static final int STRING = 44;
  public static final int PROC = 31;
  public static final int DEF = 29;
  public static final int GT = 19;
  public static final int PRINT = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "POW",
  "BAND",
  "BOR",
  "BNOT",
  "EQ",
  "GT",
  "LT",
  "LTEQ",
  "GTEQ",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "CONCAT",
  "NIL",
  "DEF",
  "LET",
  "PROC",
  "CALL",
  "PRINT",
  "PRINTLN",
  "READ",
  "READINT",
  "IF",
  "THEN",
  "ELSE",
  "CASE",
  "ID",
  "INT",
  "DOUBLE",
  "STRING",
  "CHARACTER",
  "BOOLEAN"
  };
}

