
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package smpl.syntax.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int INT = 10;
  public static final int MOD = 8;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int VAR = 12;
  public static final int DIV = 7;
  public static final int REAL = 11;
  public static final int ASSIGN = 9;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int MUL = 6;
  public static final int LPAREN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "INT",
  "REAL",
  "VAR"
  };
}

